//export const BASE_URL = process.env.NODE_ENV === "development"? " : "";
export const BASE_URL = "https://proshop-0ciz.onrender.com";
export const PRODUCTS_URL = "/api/products";
export const CATEGORIES_URL = "/api/categories";
export const USERS_URL = "/api/users";
export const ORDERS_URL = "/api/orders";
export const PAYPAL_URL = "/api/config/paypal";
export const UPLOAD_URL = "/api/upload";
//export const CART_URL = "/api/cart";
//export const LOGIN_URL = "/api/login";
//export const REGISTER_URL = "/api/register";
